name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clean
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            rm -rf gomoku && sudo docker kill $(sudo docker ps -q)
          host: ec2-52-72-176-34.compute-1.amazonaws.com
          username: ubuntu
          passphrase: ${{ secrets.AWS_PASSWORD }}
          privateKey: ${{ secrets.AWS_SSH_SECRET_KEY}}
      - name: Checkout
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            git clone https://github.com/aczh/gomoku.git && cd gomoku && git checkout ${GITHUB_REF##*/}
          host: ec2-52-72-176-34.compute-1.amazonaws.com
          username: ubuntu
          passphrase: ${{ secrets.AWS_PASSWORD }}
          privateKey: ${{ secrets.AWS_SSH_SECRET_KEY}}
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls -a
          host: ec2-52-72-176-34.compute-1.amazonaws.com
          user: ubuntu
          key: ${{ secrets.AWS_SSH_SECRET_KEY}}
          pass: ${{ secrets.AWS_PASSWORD }}
          args: "-tt -vvv"
