name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clean and checkout
        uses: appleboy/ssh-action@master
        with:
          host: ec2-52-72-176-34.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.AWS_SSH_SECRET_KEY}}
          command_timeout: "1m"
          script: |
            rm -rf gomoku
            sudo docker kill $(sudo docker ps -q)
            git clone https://github.com/aczh/gomoku.git
            cd gomoku
            echo ${GITHUB_REF##*/}
            git checkout ${GITHUB_REF##*/}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ec2-52-72-176-34.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.AWS_SSH_SECRET_KEY}}
          command_timeout: "1m"
          script: |
            cd gomoku
            nohup sudo inv run &>/dev/null &
