name: Gomoku Pytest

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test gomoku package
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install deps, pip install, pytest.
      run: |
        cd game
        python -m pip install --upgrade pip
        sudo apt-get install libmpc-dev
        pip install .
        pytest
